### ISSUE TITLE
jain i18n grids

### ISSUE THREAD

**Issue by Paueti** [lkumarjain/jain-I18n#2]
Hi,

I am guessing that the plugin doesn't support grids, right?

Could you give me some hints about how to implement a I18NGridHandler? Is it what I need, right?
Probably also to add it to the I18NComponentHandlerFactory, right?

Anything else that comes to your mind?

Thanks!
Pau

**Comment by lkumarjain** [comment]
Hi,

Please take a look at https://github.com/lkumarjain/jain-I18n-demo/blob/master/src/main/java/com/jain/i18N/definition/PersonDefinitionGrid.java for the Grid.

Thanks,
-Lokesh
