### ISSUE TITLE
dot on input prompt

### ISSUE THREAD

**Issue by radekpakula** [lkumarjain/jain-I18n#4]
When I add inputPrompt to component such like textfield,  addon insert three dots after my propmpt. Even if i have translation.  How to avoid?
Example:

```
public class I18bugUI extends I18NUI {

    @WebServlet(value = "/*", asyncSupported = true)
    @VaadinServletConfiguration(productionMode = false, ui = I18bugUI.class)
    public static class Servlet extends VaadinServlet {
    }

    @Override
    protected void initialize(VaadinRequest request) {
        final VerticalLayout layout = new VerticalLayout();
        TextField tf = new TextField();
        tf.setInputPrompt("My propt");
        layout.addComponent(new VerticalLayout(tf));
        setContent(layout);
    }
}
```

**Comment by lkumarjain** [comment]
As of now this is intentional addition of 3 dots in case of input prompt... and it is works as designed...
If I see some more request related to this will implement some configuration for this... 
or you can update this and submit...

-Lokesh

**Comment by radekpakula** [comment]
Maybe in some cases you have a right. But for example you have prompt for number field for example "0.0". In this case translation will be "0.00 ...". This can be strange for user.  I think that nothing should be added automatically without the knowledge of the programmer. (This is my suggestion) But maybe I’m wrong.

I will add configuration method to I18NProvider

Anyway great works.
